package cn.com.bsfit.frms.ds.pojo;

import java.io.Serializable;
import java.util.Date;

public class DSOnlineOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.order_id
     *
     * @mbggenerated
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.order_create_time
     *
     * @mbggenerated
     */
    private Date orderCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.money_direction
     *
     * @mbggenerated
     */
    private String moneyDirection;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.customer_id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.trans_time
     *
     * @mbggenerated
     */
    private Date transTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.trade_type
     *
     * @mbggenerated
     */
    private String tradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.pay_type
     *
     * @mbggenerated
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.prod_category
     *
     * @mbggenerated
     */
    private String prodCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.prod_sub_category
     *
     * @mbggenerated
     */
    private String prodSubCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.prod_name
     *
     * @mbggenerated
     */
    private String prodName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.pay_to_phone
     *
     * @mbggenerated
     */
    private String payToPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.pay_to_phone_prov
     *
     * @mbggenerated
     */
    private String payToPhoneProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.pay_currency_type
     *
     * @mbggenerated
     */
    private String payCurrencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.trans_amount
     *
     * @mbggenerated
     */
    private Long transAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.rep_code
     *
     * @mbggenerated
     */
    private String repCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.pay_cust_acct_id
     *
     * @mbggenerated
     */
    private String payCustAcctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.pay_cust_user_id
     *
     * @mbggenerated
     */
    private String payCustUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.pay_cust_name
     *
     * @mbggenerated
     */
    private String payCustName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.pay_cust_id_card_no
     *
     * @mbggenerated
     */
    private String payCustIdCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.pay_cust_card_no
     *
     * @mbggenerated
     */
    private String payCustCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.pay_cust_card_prov
     *
     * @mbggenerated
     */
    private String payCustCardProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.pay_cust_card_type
     *
     * @mbggenerated
     */
    private String payCustCardType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.col_cust_acct_id
     *
     * @mbggenerated
     */
    private String colCustAcctId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.col_cust_user_id
     *
     * @mbggenerated
     */
    private String colCustUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.col_cust_name
     *
     * @mbggenerated
     */
    private String colCustName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.col_cust_id_card_no
     *
     * @mbggenerated
     */
    private String colCustIdCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.col_cust_card_no
     *
     * @mbggenerated
     */
    private String colCustCardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.col_cust_card_prov
     *
     * @mbggenerated
     */
    private String colCustCardProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.shop_to_name
     *
     * @mbggenerated
     */
    private String shopToName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.shop_to_mobile
     *
     * @mbggenerated
     */
    private String shopToMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.shop_to_province
     *
     * @mbggenerated
     */
    private String shopToProvince;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.shop_to_city
     *
     * @mbggenerated
     */
    private String shopToCity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.shop_to_area
     *
     * @mbggenerated
     */
    private String shopToArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.shop_to_street
     *
     * @mbggenerated
     */
    private String shopToStreet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.last_update_time
     *
     * @mbggenerated
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.shop_to_addr
     *
     * @mbggenerated
     */
    private String shopToAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.trans_ip
     *
     * @mbggenerated
     */
    private String transIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.ip_prov
     *
     * @mbggenerated
     */
    private String ipProv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.trans_dfp
     *
     * @mbggenerated
     */
    private String transDfp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.trans_imei
     *
     * @mbggenerated
     */
    private String transImei;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.trans_mac
     *
     * @mbggenerated
     */
    private String transMac;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.refund_times
     *
     * @mbggenerated
     */
    private Integer refundTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.create_at
     *
     * @mbggenerated
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.last_update_at
     *
     * @mbggenerated
     */
    private Date lastUpdateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column online_order.last_update_by
     *
     * @mbggenerated
     */
    private String lastUpdateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table online_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    public DSOnlineOrder(String orderId, Date orderCreateTime, String moneyDirection, String customerId, Date transTime, String status, String tradeType, String payType, String prodCategory, String prodSubCategory, String prodName, String payToPhone, String payToPhoneProv, String payCurrencyType, Long transAmount, String repCode, String payCustAcctId, String payCustUserId, String payCustName, String payCustIdCardNo, String payCustCardNo, String payCustCardProv, String payCustCardType, String colCustAcctId, String colCustUserId, String colCustName, String colCustIdCardNo, String colCustCardNo, String colCustCardProv, String shopToName, String shopToMobile, String shopToProvince, String shopToCity, String shopToArea, String shopToStreet, Date lastUpdateTime, String shopToAddr, String transIp, String ipProv, String transDfp, String transImei, String transMac, Integer refundTimes, Date createAt, String createBy, Date lastUpdateAt, String lastUpdateBy) {
        this.orderId = orderId;
        this.orderCreateTime = orderCreateTime;
        this.moneyDirection = moneyDirection;
        this.customerId = customerId;
        this.transTime = transTime;
        this.status = status;
        this.tradeType = tradeType;
        this.payType = payType;
        this.prodCategory = prodCategory;
        this.prodSubCategory = prodSubCategory;
        this.prodName = prodName;
        this.payToPhone = payToPhone;
        this.payToPhoneProv = payToPhoneProv;
        this.payCurrencyType = payCurrencyType;
        this.transAmount = transAmount;
        this.repCode = repCode;
        this.payCustAcctId = payCustAcctId;
        this.payCustUserId = payCustUserId;
        this.payCustName = payCustName;
        this.payCustIdCardNo = payCustIdCardNo;
        this.payCustCardNo = payCustCardNo;
        this.payCustCardProv = payCustCardProv;
        this.payCustCardType = payCustCardType;
        this.colCustAcctId = colCustAcctId;
        this.colCustUserId = colCustUserId;
        this.colCustName = colCustName;
        this.colCustIdCardNo = colCustIdCardNo;
        this.colCustCardNo = colCustCardNo;
        this.colCustCardProv = colCustCardProv;
        this.shopToName = shopToName;
        this.shopToMobile = shopToMobile;
        this.shopToProvince = shopToProvince;
        this.shopToCity = shopToCity;
        this.shopToArea = shopToArea;
        this.shopToStreet = shopToStreet;
        this.lastUpdateTime = lastUpdateTime;
        this.shopToAddr = shopToAddr;
        this.transIp = transIp;
        this.ipProv = ipProv;
        this.transDfp = transDfp;
        this.transImei = transImei;
        this.transMac = transMac;
        this.refundTimes = refundTimes;
        this.createAt = createAt;
        this.createBy = createBy;
        this.lastUpdateAt = lastUpdateAt;
        this.lastUpdateBy = lastUpdateBy;
    }

    public DSOnlineOrder() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.order_id
     *
     * @return the value of online_order.order_id
     *
     * @mbggenerated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.order_id
     *
     * @param orderId the value for online_order.order_id
     *
     * @mbggenerated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.order_create_time
     *
     * @return the value of online_order.order_create_time
     *
     * @mbggenerated
     */
    public Date getOrderCreateTime() {
        return orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.order_create_time
     *
     * @param orderCreateTime the value for online_order.order_create_time
     *
     * @mbggenerated
     */
    public void setOrderCreateTime(Date orderCreateTime) {
        this.orderCreateTime = orderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.money_direction
     *
     * @return the value of online_order.money_direction
     *
     * @mbggenerated
     */
    public String getMoneyDirection() {
        return moneyDirection;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.money_direction
     *
     * @param moneyDirection the value for online_order.money_direction
     *
     * @mbggenerated
     */
    public void setMoneyDirection(String moneyDirection) {
        this.moneyDirection = moneyDirection == null ? null : moneyDirection.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.customer_id
     *
     * @return the value of online_order.customer_id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.customer_id
     *
     * @param customerId the value for online_order.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.trans_time
     *
     * @return the value of online_order.trans_time
     *
     * @mbggenerated
     */
    public Date getTransTime() {
        return transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.trans_time
     *
     * @param transTime the value for online_order.trans_time
     *
     * @mbggenerated
     */
    public void setTransTime(Date transTime) {
        this.transTime = transTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.status
     *
     * @return the value of online_order.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.status
     *
     * @param status the value for online_order.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.trade_type
     *
     * @return the value of online_order.trade_type
     *
     * @mbggenerated
     */
    public String getTradeType() {
        return tradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.trade_type
     *
     * @param tradeType the value for online_order.trade_type
     *
     * @mbggenerated
     */
    public void setTradeType(String tradeType) {
        this.tradeType = tradeType == null ? null : tradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.pay_type
     *
     * @return the value of online_order.pay_type
     *
     * @mbggenerated
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.pay_type
     *
     * @param payType the value for online_order.pay_type
     *
     * @mbggenerated
     */
    public void setPayType(String payType) {
        this.payType = payType == null ? null : payType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.prod_category
     *
     * @return the value of online_order.prod_category
     *
     * @mbggenerated
     */
    public String getProdCategory() {
        return prodCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.prod_category
     *
     * @param prodCategory the value for online_order.prod_category
     *
     * @mbggenerated
     */
    public void setProdCategory(String prodCategory) {
        this.prodCategory = prodCategory == null ? null : prodCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.prod_sub_category
     *
     * @return the value of online_order.prod_sub_category
     *
     * @mbggenerated
     */
    public String getProdSubCategory() {
        return prodSubCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.prod_sub_category
     *
     * @param prodSubCategory the value for online_order.prod_sub_category
     *
     * @mbggenerated
     */
    public void setProdSubCategory(String prodSubCategory) {
        this.prodSubCategory = prodSubCategory == null ? null : prodSubCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.prod_name
     *
     * @return the value of online_order.prod_name
     *
     * @mbggenerated
     */
    public String getProdName() {
        return prodName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.prod_name
     *
     * @param prodName the value for online_order.prod_name
     *
     * @mbggenerated
     */
    public void setProdName(String prodName) {
        this.prodName = prodName == null ? null : prodName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.pay_to_phone
     *
     * @return the value of online_order.pay_to_phone
     *
     * @mbggenerated
     */
    public String getPayToPhone() {
        return payToPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.pay_to_phone
     *
     * @param payToPhone the value for online_order.pay_to_phone
     *
     * @mbggenerated
     */
    public void setPayToPhone(String payToPhone) {
        this.payToPhone = payToPhone == null ? null : payToPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.pay_to_phone_prov
     *
     * @return the value of online_order.pay_to_phone_prov
     *
     * @mbggenerated
     */
    public String getPayToPhoneProv() {
        return payToPhoneProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.pay_to_phone_prov
     *
     * @param payToPhoneProv the value for online_order.pay_to_phone_prov
     *
     * @mbggenerated
     */
    public void setPayToPhoneProv(String payToPhoneProv) {
        this.payToPhoneProv = payToPhoneProv == null ? null : payToPhoneProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.pay_currency_type
     *
     * @return the value of online_order.pay_currency_type
     *
     * @mbggenerated
     */
    public String getPayCurrencyType() {
        return payCurrencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.pay_currency_type
     *
     * @param payCurrencyType the value for online_order.pay_currency_type
     *
     * @mbggenerated
     */
    public void setPayCurrencyType(String payCurrencyType) {
        this.payCurrencyType = payCurrencyType == null ? null : payCurrencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.trans_amount
     *
     * @return the value of online_order.trans_amount
     *
     * @mbggenerated
     */
    public Long getTransAmount() {
        return transAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.trans_amount
     *
     * @param transAmount the value for online_order.trans_amount
     *
     * @mbggenerated
     */
    public void setTransAmount(Long transAmount) {
        this.transAmount = transAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.rep_code
     *
     * @return the value of online_order.rep_code
     *
     * @mbggenerated
     */
    public String getRepCode() {
        return repCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.rep_code
     *
     * @param repCode the value for online_order.rep_code
     *
     * @mbggenerated
     */
    public void setRepCode(String repCode) {
        this.repCode = repCode == null ? null : repCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.pay_cust_acct_id
     *
     * @return the value of online_order.pay_cust_acct_id
     *
     * @mbggenerated
     */
    public String getPayCustAcctId() {
        return payCustAcctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.pay_cust_acct_id
     *
     * @param payCustAcctId the value for online_order.pay_cust_acct_id
     *
     * @mbggenerated
     */
    public void setPayCustAcctId(String payCustAcctId) {
        this.payCustAcctId = payCustAcctId == null ? null : payCustAcctId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.pay_cust_user_id
     *
     * @return the value of online_order.pay_cust_user_id
     *
     * @mbggenerated
     */
    public String getPayCustUserId() {
        return payCustUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.pay_cust_user_id
     *
     * @param payCustUserId the value for online_order.pay_cust_user_id
     *
     * @mbggenerated
     */
    public void setPayCustUserId(String payCustUserId) {
        this.payCustUserId = payCustUserId == null ? null : payCustUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.pay_cust_name
     *
     * @return the value of online_order.pay_cust_name
     *
     * @mbggenerated
     */
    public String getPayCustName() {
        return payCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.pay_cust_name
     *
     * @param payCustName the value for online_order.pay_cust_name
     *
     * @mbggenerated
     */
    public void setPayCustName(String payCustName) {
        this.payCustName = payCustName == null ? null : payCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.pay_cust_id_card_no
     *
     * @return the value of online_order.pay_cust_id_card_no
     *
     * @mbggenerated
     */
    public String getPayCustIdCardNo() {
        return payCustIdCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.pay_cust_id_card_no
     *
     * @param payCustIdCardNo the value for online_order.pay_cust_id_card_no
     *
     * @mbggenerated
     */
    public void setPayCustIdCardNo(String payCustIdCardNo) {
        this.payCustIdCardNo = payCustIdCardNo == null ? null : payCustIdCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.pay_cust_card_no
     *
     * @return the value of online_order.pay_cust_card_no
     *
     * @mbggenerated
     */
    public String getPayCustCardNo() {
        return payCustCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.pay_cust_card_no
     *
     * @param payCustCardNo the value for online_order.pay_cust_card_no
     *
     * @mbggenerated
     */
    public void setPayCustCardNo(String payCustCardNo) {
        this.payCustCardNo = payCustCardNo == null ? null : payCustCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.pay_cust_card_prov
     *
     * @return the value of online_order.pay_cust_card_prov
     *
     * @mbggenerated
     */
    public String getPayCustCardProv() {
        return payCustCardProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.pay_cust_card_prov
     *
     * @param payCustCardProv the value for online_order.pay_cust_card_prov
     *
     * @mbggenerated
     */
    public void setPayCustCardProv(String payCustCardProv) {
        this.payCustCardProv = payCustCardProv == null ? null : payCustCardProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.pay_cust_card_type
     *
     * @return the value of online_order.pay_cust_card_type
     *
     * @mbggenerated
     */
    public String getPayCustCardType() {
        return payCustCardType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.pay_cust_card_type
     *
     * @param payCustCardType the value for online_order.pay_cust_card_type
     *
     * @mbggenerated
     */
    public void setPayCustCardType(String payCustCardType) {
        this.payCustCardType = payCustCardType == null ? null : payCustCardType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.col_cust_acct_id
     *
     * @return the value of online_order.col_cust_acct_id
     *
     * @mbggenerated
     */
    public String getColCustAcctId() {
        return colCustAcctId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.col_cust_acct_id
     *
     * @param colCustAcctId the value for online_order.col_cust_acct_id
     *
     * @mbggenerated
     */
    public void setColCustAcctId(String colCustAcctId) {
        this.colCustAcctId = colCustAcctId == null ? null : colCustAcctId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.col_cust_user_id
     *
     * @return the value of online_order.col_cust_user_id
     *
     * @mbggenerated
     */
    public String getColCustUserId() {
        return colCustUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.col_cust_user_id
     *
     * @param colCustUserId the value for online_order.col_cust_user_id
     *
     * @mbggenerated
     */
    public void setColCustUserId(String colCustUserId) {
        this.colCustUserId = colCustUserId == null ? null : colCustUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.col_cust_name
     *
     * @return the value of online_order.col_cust_name
     *
     * @mbggenerated
     */
    public String getColCustName() {
        return colCustName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.col_cust_name
     *
     * @param colCustName the value for online_order.col_cust_name
     *
     * @mbggenerated
     */
    public void setColCustName(String colCustName) {
        this.colCustName = colCustName == null ? null : colCustName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.col_cust_id_card_no
     *
     * @return the value of online_order.col_cust_id_card_no
     *
     * @mbggenerated
     */
    public String getColCustIdCardNo() {
        return colCustIdCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.col_cust_id_card_no
     *
     * @param colCustIdCardNo the value for online_order.col_cust_id_card_no
     *
     * @mbggenerated
     */
    public void setColCustIdCardNo(String colCustIdCardNo) {
        this.colCustIdCardNo = colCustIdCardNo == null ? null : colCustIdCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.col_cust_card_no
     *
     * @return the value of online_order.col_cust_card_no
     *
     * @mbggenerated
     */
    public String getColCustCardNo() {
        return colCustCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.col_cust_card_no
     *
     * @param colCustCardNo the value for online_order.col_cust_card_no
     *
     * @mbggenerated
     */
    public void setColCustCardNo(String colCustCardNo) {
        this.colCustCardNo = colCustCardNo == null ? null : colCustCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.col_cust_card_prov
     *
     * @return the value of online_order.col_cust_card_prov
     *
     * @mbggenerated
     */
    public String getColCustCardProv() {
        return colCustCardProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.col_cust_card_prov
     *
     * @param colCustCardProv the value for online_order.col_cust_card_prov
     *
     * @mbggenerated
     */
    public void setColCustCardProv(String colCustCardProv) {
        this.colCustCardProv = colCustCardProv == null ? null : colCustCardProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.shop_to_name
     *
     * @return the value of online_order.shop_to_name
     *
     * @mbggenerated
     */
    public String getShopToName() {
        return shopToName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.shop_to_name
     *
     * @param shopToName the value for online_order.shop_to_name
     *
     * @mbggenerated
     */
    public void setShopToName(String shopToName) {
        this.shopToName = shopToName == null ? null : shopToName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.shop_to_mobile
     *
     * @return the value of online_order.shop_to_mobile
     *
     * @mbggenerated
     */
    public String getShopToMobile() {
        return shopToMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.shop_to_mobile
     *
     * @param shopToMobile the value for online_order.shop_to_mobile
     *
     * @mbggenerated
     */
    public void setShopToMobile(String shopToMobile) {
        this.shopToMobile = shopToMobile == null ? null : shopToMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.shop_to_province
     *
     * @return the value of online_order.shop_to_province
     *
     * @mbggenerated
     */
    public String getShopToProvince() {
        return shopToProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.shop_to_province
     *
     * @param shopToProvince the value for online_order.shop_to_province
     *
     * @mbggenerated
     */
    public void setShopToProvince(String shopToProvince) {
        this.shopToProvince = shopToProvince == null ? null : shopToProvince.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.shop_to_city
     *
     * @return the value of online_order.shop_to_city
     *
     * @mbggenerated
     */
    public String getShopToCity() {
        return shopToCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.shop_to_city
     *
     * @param shopToCity the value for online_order.shop_to_city
     *
     * @mbggenerated
     */
    public void setShopToCity(String shopToCity) {
        this.shopToCity = shopToCity == null ? null : shopToCity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.shop_to_area
     *
     * @return the value of online_order.shop_to_area
     *
     * @mbggenerated
     */
    public String getShopToArea() {
        return shopToArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.shop_to_area
     *
     * @param shopToArea the value for online_order.shop_to_area
     *
     * @mbggenerated
     */
    public void setShopToArea(String shopToArea) {
        this.shopToArea = shopToArea == null ? null : shopToArea.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.shop_to_street
     *
     * @return the value of online_order.shop_to_street
     *
     * @mbggenerated
     */
    public String getShopToStreet() {
        return shopToStreet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.shop_to_street
     *
     * @param shopToStreet the value for online_order.shop_to_street
     *
     * @mbggenerated
     */
    public void setShopToStreet(String shopToStreet) {
        this.shopToStreet = shopToStreet == null ? null : shopToStreet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.last_update_time
     *
     * @return the value of online_order.last_update_time
     *
     * @mbggenerated
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.last_update_time
     *
     * @param lastUpdateTime the value for online_order.last_update_time
     *
     * @mbggenerated
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.shop_to_addr
     *
     * @return the value of online_order.shop_to_addr
     *
     * @mbggenerated
     */
    public String getShopToAddr() {
        return shopToAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.shop_to_addr
     *
     * @param shopToAddr the value for online_order.shop_to_addr
     *
     * @mbggenerated
     */
    public void setShopToAddr(String shopToAddr) {
        this.shopToAddr = shopToAddr == null ? null : shopToAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.trans_ip
     *
     * @return the value of online_order.trans_ip
     *
     * @mbggenerated
     */
    public String getTransIp() {
        return transIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.trans_ip
     *
     * @param transIp the value for online_order.trans_ip
     *
     * @mbggenerated
     */
    public void setTransIp(String transIp) {
        this.transIp = transIp == null ? null : transIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.ip_prov
     *
     * @return the value of online_order.ip_prov
     *
     * @mbggenerated
     */
    public String getIpProv() {
        return ipProv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.ip_prov
     *
     * @param ipProv the value for online_order.ip_prov
     *
     * @mbggenerated
     */
    public void setIpProv(String ipProv) {
        this.ipProv = ipProv == null ? null : ipProv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.trans_dfp
     *
     * @return the value of online_order.trans_dfp
     *
     * @mbggenerated
     */
    public String getTransDfp() {
        return transDfp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.trans_dfp
     *
     * @param transDfp the value for online_order.trans_dfp
     *
     * @mbggenerated
     */
    public void setTransDfp(String transDfp) {
        this.transDfp = transDfp == null ? null : transDfp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.trans_imei
     *
     * @return the value of online_order.trans_imei
     *
     * @mbggenerated
     */
    public String getTransImei() {
        return transImei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.trans_imei
     *
     * @param transImei the value for online_order.trans_imei
     *
     * @mbggenerated
     */
    public void setTransImei(String transImei) {
        this.transImei = transImei == null ? null : transImei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.trans_mac
     *
     * @return the value of online_order.trans_mac
     *
     * @mbggenerated
     */
    public String getTransMac() {
        return transMac;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.trans_mac
     *
     * @param transMac the value for online_order.trans_mac
     *
     * @mbggenerated
     */
    public void setTransMac(String transMac) {
        this.transMac = transMac == null ? null : transMac.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.refund_times
     *
     * @return the value of online_order.refund_times
     *
     * @mbggenerated
     */
    public Integer getRefundTimes() {
        return refundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.refund_times
     *
     * @param refundTimes the value for online_order.refund_times
     *
     * @mbggenerated
     */
    public void setRefundTimes(Integer refundTimes) {
        this.refundTimes = refundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.create_at
     *
     * @return the value of online_order.create_at
     *
     * @mbggenerated
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.create_at
     *
     * @param createAt the value for online_order.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.create_by
     *
     * @return the value of online_order.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.create_by
     *
     * @param createBy the value for online_order.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.last_update_at
     *
     * @return the value of online_order.last_update_at
     *
     * @mbggenerated
     */
    public Date getLastUpdateAt() {
        return lastUpdateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.last_update_at
     *
     * @param lastUpdateAt the value for online_order.last_update_at
     *
     * @mbggenerated
     */
    public void setLastUpdateAt(Date lastUpdateAt) {
        this.lastUpdateAt = lastUpdateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column online_order.last_update_by
     *
     * @return the value of online_order.last_update_by
     *
     * @mbggenerated
     */
    public String getLastUpdateBy() {
        return lastUpdateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column online_order.last_update_by
     *
     * @param lastUpdateBy the value for online_order.last_update_by
     *
     * @mbggenerated
     */
    public void setLastUpdateBy(String lastUpdateBy) {
        this.lastUpdateBy = lastUpdateBy == null ? null : lastUpdateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DSOnlineOrder other = (DSOnlineOrder) that;
        return (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getOrderCreateTime() == null ? other.getOrderCreateTime() == null : this.getOrderCreateTime().equals(other.getOrderCreateTime()))
            && (this.getMoneyDirection() == null ? other.getMoneyDirection() == null : this.getMoneyDirection().equals(other.getMoneyDirection()))
            && (this.getCustomerId() == null ? other.getCustomerId() == null : this.getCustomerId().equals(other.getCustomerId()))
            && (this.getTransTime() == null ? other.getTransTime() == null : this.getTransTime().equals(other.getTransTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getTradeType() == null ? other.getTradeType() == null : this.getTradeType().equals(other.getTradeType()))
            && (this.getPayType() == null ? other.getPayType() == null : this.getPayType().equals(other.getPayType()))
            && (this.getProdCategory() == null ? other.getProdCategory() == null : this.getProdCategory().equals(other.getProdCategory()))
            && (this.getProdSubCategory() == null ? other.getProdSubCategory() == null : this.getProdSubCategory().equals(other.getProdSubCategory()))
            && (this.getProdName() == null ? other.getProdName() == null : this.getProdName().equals(other.getProdName()))
            && (this.getPayToPhone() == null ? other.getPayToPhone() == null : this.getPayToPhone().equals(other.getPayToPhone()))
            && (this.getPayToPhoneProv() == null ? other.getPayToPhoneProv() == null : this.getPayToPhoneProv().equals(other.getPayToPhoneProv()))
            && (this.getPayCurrencyType() == null ? other.getPayCurrencyType() == null : this.getPayCurrencyType().equals(other.getPayCurrencyType()))
            && (this.getTransAmount() == null ? other.getTransAmount() == null : this.getTransAmount().equals(other.getTransAmount()))
            && (this.getRepCode() == null ? other.getRepCode() == null : this.getRepCode().equals(other.getRepCode()))
            && (this.getPayCustAcctId() == null ? other.getPayCustAcctId() == null : this.getPayCustAcctId().equals(other.getPayCustAcctId()))
            && (this.getPayCustUserId() == null ? other.getPayCustUserId() == null : this.getPayCustUserId().equals(other.getPayCustUserId()))
            && (this.getPayCustName() == null ? other.getPayCustName() == null : this.getPayCustName().equals(other.getPayCustName()))
            && (this.getPayCustIdCardNo() == null ? other.getPayCustIdCardNo() == null : this.getPayCustIdCardNo().equals(other.getPayCustIdCardNo()))
            && (this.getPayCustCardNo() == null ? other.getPayCustCardNo() == null : this.getPayCustCardNo().equals(other.getPayCustCardNo()))
            && (this.getPayCustCardProv() == null ? other.getPayCustCardProv() == null : this.getPayCustCardProv().equals(other.getPayCustCardProv()))
            && (this.getPayCustCardType() == null ? other.getPayCustCardType() == null : this.getPayCustCardType().equals(other.getPayCustCardType()))
            && (this.getColCustAcctId() == null ? other.getColCustAcctId() == null : this.getColCustAcctId().equals(other.getColCustAcctId()))
            && (this.getColCustUserId() == null ? other.getColCustUserId() == null : this.getColCustUserId().equals(other.getColCustUserId()))
            && (this.getColCustName() == null ? other.getColCustName() == null : this.getColCustName().equals(other.getColCustName()))
            && (this.getColCustIdCardNo() == null ? other.getColCustIdCardNo() == null : this.getColCustIdCardNo().equals(other.getColCustIdCardNo()))
            && (this.getColCustCardNo() == null ? other.getColCustCardNo() == null : this.getColCustCardNo().equals(other.getColCustCardNo()))
            && (this.getColCustCardProv() == null ? other.getColCustCardProv() == null : this.getColCustCardProv().equals(other.getColCustCardProv()))
            && (this.getShopToName() == null ? other.getShopToName() == null : this.getShopToName().equals(other.getShopToName()))
            && (this.getShopToMobile() == null ? other.getShopToMobile() == null : this.getShopToMobile().equals(other.getShopToMobile()))
            && (this.getShopToProvince() == null ? other.getShopToProvince() == null : this.getShopToProvince().equals(other.getShopToProvince()))
            && (this.getShopToCity() == null ? other.getShopToCity() == null : this.getShopToCity().equals(other.getShopToCity()))
            && (this.getShopToArea() == null ? other.getShopToArea() == null : this.getShopToArea().equals(other.getShopToArea()))
            && (this.getShopToStreet() == null ? other.getShopToStreet() == null : this.getShopToStreet().equals(other.getShopToStreet()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getShopToAddr() == null ? other.getShopToAddr() == null : this.getShopToAddr().equals(other.getShopToAddr()))
            && (this.getTransIp() == null ? other.getTransIp() == null : this.getTransIp().equals(other.getTransIp()))
            && (this.getIpProv() == null ? other.getIpProv() == null : this.getIpProv().equals(other.getIpProv()))
            && (this.getTransDfp() == null ? other.getTransDfp() == null : this.getTransDfp().equals(other.getTransDfp()))
            && (this.getTransImei() == null ? other.getTransImei() == null : this.getTransImei().equals(other.getTransImei()))
            && (this.getTransMac() == null ? other.getTransMac() == null : this.getTransMac().equals(other.getTransMac()))
            && (this.getRefundTimes() == null ? other.getRefundTimes() == null : this.getRefundTimes().equals(other.getRefundTimes()))
            && (this.getCreateAt() == null ? other.getCreateAt() == null : this.getCreateAt().equals(other.getCreateAt()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getLastUpdateAt() == null ? other.getLastUpdateAt() == null : this.getLastUpdateAt().equals(other.getLastUpdateAt()))
            && (this.getLastUpdateBy() == null ? other.getLastUpdateBy() == null : this.getLastUpdateBy().equals(other.getLastUpdateBy()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table online_order
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getOrderCreateTime() == null) ? 0 : getOrderCreateTime().hashCode());
        result = prime * result + ((getMoneyDirection() == null) ? 0 : getMoneyDirection().hashCode());
        result = prime * result + ((getCustomerId() == null) ? 0 : getCustomerId().hashCode());
        result = prime * result + ((getTransTime() == null) ? 0 : getTransTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getTradeType() == null) ? 0 : getTradeType().hashCode());
        result = prime * result + ((getPayType() == null) ? 0 : getPayType().hashCode());
        result = prime * result + ((getProdCategory() == null) ? 0 : getProdCategory().hashCode());
        result = prime * result + ((getProdSubCategory() == null) ? 0 : getProdSubCategory().hashCode());
        result = prime * result + ((getProdName() == null) ? 0 : getProdName().hashCode());
        result = prime * result + ((getPayToPhone() == null) ? 0 : getPayToPhone().hashCode());
        result = prime * result + ((getPayToPhoneProv() == null) ? 0 : getPayToPhoneProv().hashCode());
        result = prime * result + ((getPayCurrencyType() == null) ? 0 : getPayCurrencyType().hashCode());
        result = prime * result + ((getTransAmount() == null) ? 0 : getTransAmount().hashCode());
        result = prime * result + ((getRepCode() == null) ? 0 : getRepCode().hashCode());
        result = prime * result + ((getPayCustAcctId() == null) ? 0 : getPayCustAcctId().hashCode());
        result = prime * result + ((getPayCustUserId() == null) ? 0 : getPayCustUserId().hashCode());
        result = prime * result + ((getPayCustName() == null) ? 0 : getPayCustName().hashCode());
        result = prime * result + ((getPayCustIdCardNo() == null) ? 0 : getPayCustIdCardNo().hashCode());
        result = prime * result + ((getPayCustCardNo() == null) ? 0 : getPayCustCardNo().hashCode());
        result = prime * result + ((getPayCustCardProv() == null) ? 0 : getPayCustCardProv().hashCode());
        result = prime * result + ((getPayCustCardType() == null) ? 0 : getPayCustCardType().hashCode());
        result = prime * result + ((getColCustAcctId() == null) ? 0 : getColCustAcctId().hashCode());
        result = prime * result + ((getColCustUserId() == null) ? 0 : getColCustUserId().hashCode());
        result = prime * result + ((getColCustName() == null) ? 0 : getColCustName().hashCode());
        result = prime * result + ((getColCustIdCardNo() == null) ? 0 : getColCustIdCardNo().hashCode());
        result = prime * result + ((getColCustCardNo() == null) ? 0 : getColCustCardNo().hashCode());
        result = prime * result + ((getColCustCardProv() == null) ? 0 : getColCustCardProv().hashCode());
        result = prime * result + ((getShopToName() == null) ? 0 : getShopToName().hashCode());
        result = prime * result + ((getShopToMobile() == null) ? 0 : getShopToMobile().hashCode());
        result = prime * result + ((getShopToProvince() == null) ? 0 : getShopToProvince().hashCode());
        result = prime * result + ((getShopToCity() == null) ? 0 : getShopToCity().hashCode());
        result = prime * result + ((getShopToArea() == null) ? 0 : getShopToArea().hashCode());
        result = prime * result + ((getShopToStreet() == null) ? 0 : getShopToStreet().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getShopToAddr() == null) ? 0 : getShopToAddr().hashCode());
        result = prime * result + ((getTransIp() == null) ? 0 : getTransIp().hashCode());
        result = prime * result + ((getIpProv() == null) ? 0 : getIpProv().hashCode());
        result = prime * result + ((getTransDfp() == null) ? 0 : getTransDfp().hashCode());
        result = prime * result + ((getTransImei() == null) ? 0 : getTransImei().hashCode());
        result = prime * result + ((getTransMac() == null) ? 0 : getTransMac().hashCode());
        result = prime * result + ((getRefundTimes() == null) ? 0 : getRefundTimes().hashCode());
        result = prime * result + ((getCreateAt() == null) ? 0 : getCreateAt().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getLastUpdateAt() == null) ? 0 : getLastUpdateAt().hashCode());
        result = prime * result + ((getLastUpdateBy() == null) ? 0 : getLastUpdateBy().hashCode());
        return result;
    }
}